discourse/.github

workflow-templates/plugin-tests.yml
Just a bit of a clean up.
Btw. the previous "Update CI" run has spectacularly failed - https://github.com/discourse/.github/actions/runs/318285548
I haven't triggered it again since merging this PR will push out changes anyway.
=> DEV: Remove env.BUILD_TYPE

.github/workflows/update_ci.yml, workflow-templates/plugin-linting.yml, workflow-templates/plugin-tests.yml
Includes:
* DEV: Fix linting issues
* DEV: No need for the extra checkout step?
* DEV: Update ruby to 2.7
* DEV: Use the versioned `actions/checkout` (v2)
* DEV: Move the OS out of the build matrix
* DEV: Use `ruby/setup-ruby`
* DEV: Add Ember template lint stage
* DEV: Add English locale lint stage
=> Various improvements

workflow-templates/plugin-linting.yml, workflow-templates/plugin-tests.yml
I'm not enabling prettier for **all** files yet. It'd be nice to have auto-fixing implemented before that.
=> DEV: Check for files not dirs before rspec/qunit

workflow-templates/plugin-linting.yml, workflow-templates/plugin-tests.yml
See https://github.com/discourse/discourse-data-explorer/pull/129#discussion_r680028095 for more info
=> FIX: `ls dir/**/*` would not find files couple levels deep

workflow-templates/plugin-linting.yml, workflow-templates/plugin-tests.yml
Use only the `main` branch, update node to 16.x, and use yarn cache.
=> DEV: Update workflows

.github/workflows/update_ci.yml
=> Correct workflow syntax

workflow-templates/plugin-linting.yml, workflow-templates/plugin-tests.yml
=> DEV: Add latest improvements from core

workflow-templates/plugin-tests.yml
Changes tested at https://github.com/discourse/discourse-solved/pull/178
=> Introduce Ember-CLI frontend tests

.github/workflows/update_ci.yml
=> DEV: Update the workflow

theme-workflow-templates/component-tests.yml
Tested in https://github.com/discourse/DiscoTOC/pull/40 (tests) and https://github.com/discourse/discourse-theme-skeleton/pull/1 (no tests)
=> DEV: Don't run test steps if there are no tests

.github/workflows/discourse-plugin.yml, .github/workflows/discourse-theme.yml, .github/workflows/test-templates.yml
Allows to test workflow changes without manually opening draft PRs to random plugins/themes
=> DEV: Add CI workflow to test template workflows

.github/workflows/discourse-plugin.yml
See https://github.com/discourse/discourse/pull/20699
=> DEV: Add zeitwerk eager-load check to plugin workflow

.github/workflows/discourse-plugin.yml
For testing stuff with core branches/tags other than `main`.
=> FEATURE: Allow custom core refs

.github/workflows/discourse-plugin.yml
https://github.com/discourse/discourse/pull/22151
=> Add Zeitwerk reloading check

.github/workflows/discourse-plugin.yml, .github/workflows/discourse-theme.yml
Ref https://github.com/discourse/discourse/pull/24416
=> DEV: Silence successful db:migrate output

.github/workflows/discourse-theme.yml
This brings the qunit tests in line with the system specs
=> Skip installing/updating child components in theme tests

.github/workflows/discourse-plugin.yml, .github/workflows/discourse-theme.yml
We no longer include it in the docker image
=> DEV: Remove "Remove Chromium" steps

actions/clone-additional-plugins/action.yml
Example:
```json
{
"tests": {
"requiredPlugins": [
"https://github.com/discourse/discourse-calendar",
{
"url": "https://github.com/discourse/discourse-ai",
"branch": "more-topics"
}
]
}
}
```
=> FEATURE: Custom branch support in clone-additonal-plugins

.github/workflows/discourse-plugin.yml
since the issue is now fixed (and we rolled out the new version everywhere)
=> DEV: Merge ember template lint steps

.github/workflows/discourse-plugin.yml
This change allows us to configure the runner used for the workflow.
=> Add `runs-on` as workflow_call input

.github/workflows/discourse-theme.yml
Regressed in 2d9f5aeae2dbabca0d6b5cf88d3f8d61a3113a12
=> Fix theme system tests not running

.github/workflows/discourse-plugin.yml, .github/workflows/discourse-theme.yml
Requires: https://github.com/discourse/discourse/pull/32390
=> Run ruby tests in parallel by default

.github/workflows/discourse-plugin.yml, .github/workflows/discourse-theme.yml
The current workflows were only uploading pngs.
=> DEV: playwrights can also upload webm and zip

.github/workflows/discourse-plugin.yml, .github/workflows/discourse-theme.yml
Im not sure glob was working correctly.
=> DEV: paths without globs

.github/workflows/discourse-plugin.yml, .github/workflows/discourse-theme.yml
See https://github.com/discourse/discourse/pull/33973
=> PERF: Use pre-built JS assets

.github/workflows/discourse-plugin.yml, .github/workflows/discourse-theme.yml
https://meta.discourse.org/t/384272
=> DEV: Update default core branch from `tests-passed` to `latest`
