discourse/.github

workflow-templates/plugin-linting.yml
workflow-templates/plugin-tests.yml

Triggering builds on push to any branch meant that everything was run twice on new PRs. For example see: https://github.com/discourse/discourse-voting/pull/61/checks (10 checks instead of 5)
(future TODO: change it to `main` when the times comes 😃)

FIX: Trigger tests/linting only on `master` pushes

---

.github/workflows/update_ci.yml

With the lack of a GitHub-official way to update repositories with template changes in the `.github` repository yet (and it looks like GitHub intends that feature to be Enterprise-only when they do roll it out), here's a PR rolling our own method. The main advantage here is we:
1. have a guard against incorrectly formatted PRs on official plugins, which, if merged, break core builds, and
2. have a single source of truth for our official plugin CI that's fully automated.
When these changes are merged to `master`, any changes to a `.yml` file in the `workflow-templates` directory will be copied to each official plugin listed under `matrix.repositories`. The nice thing about using the matrix approach is pushing these changes out happens in parallel.
As a v1, this assumes the proper linting …

FEATURE: Automatically update CI on official plugins

---

workflow-templates/plugin-linting.yml
workflow-templates/plugin-tests.yml

Simple change to the CI workflows -- add main as an approved branch to run workflows on. This is a forward-looking commit with new repositories having `main` vs `master` as of October 1st.

DEV: Add main to workflow branches

---

.github/workflows/update_ci.yml
workflow-templates/plugin-linting.yml

Prettier does not currently have a method to skip running if no matches found. Some official plugins do not have an `assets` folder, so prettier will currently fail. This commit adds a directory check prior to running the prettier command, which should skip prettier if the assets directory does not exist.

FIX: Skip prettier when no assets

---

workflow-templates/plugin-linting.yml

Using `[ -d "assets"] && yarn prettier ...` still returned `exit 1` if the directory was not found. This commit introduces logic to cleanly exit if `assets/` does not exist.

FIX: Return exit 0 when assets not found

---

workflow-templates/plugin-linting.yml

This was a problem because the if-then block did not have a proper end.
This commit also simplifies the code a bit because `exit 0` did not do
anything.
```
yarn run v1.22.5
$ /home/runner/work/discourse-encrypt/discourse-encrypt/node_modules/.bin/prettier -v
2.1.2
Done in 0.24s.
/home/runner/work/_temp/7c858813-e0e9-45b7-9b7f-3e87943c87e4.sh: line 8: syntax error: unexpected end of file
Error: Process completed with exit code 2.
```

FIX: End if-then block and simplify code

---

workflow-templates/plugin-tests.yml

https://github.com/actions/cache/issues/381#issuecomment-662597653
v1 has issues with slow cache restoration. Tested with v2 in a branch on `knowledge-explorer` and it seemed to fire up quite a bit faster.

DEV: Upgrade to actions/cache@v2

---

workflow-templates/plugin-tests.yml

There's just one target. This removes code related to the deleted "core" target and all "target" parameterization.

DEV: Remove dead code from plugin-tests.yml

---

.github/workflows/update_ci.yml

Adds "discourse-subscriptions" to our CI workflows since it is becoming official.

DEV: Add discourse-subscriptions as official

---

.github/workflows/update_ci.yml

@CvX I fixed up the permissions issue -- was a missing permission on the token we use.
That being said, we have PR requirements for a handful of official plugins and it sounds like we're going to move that way for all plugins soon. I whipped up this PR to move from committing to master to creating a PR from a branch. I wasn't able to test this on my personal account as the APIs are different (in fact I couldn't even locate the proper one). Mind having a look?

FEATURE: Migrate to PRs for CI Updates

---

workflow-templates/plugin-linting.yml

Prettier and ESLint were not running on the `test` directory, which could cause broken core builds.

FIX: Ensure linting runs on test directory

---

.github/workflows/update_ci.yml

PR reduces the number of concurrent requests made to update our CI to avoid hitting any GitHub rate limits. Will start at 2 for testing and could bump to probably 10 once this is confirmed to work.

FIX: Reduce concurrency to avoid rate limits

---

.github/workflows/update_ci.yml

Follow-up to #16 -- even two parallel jobs was too much. Reducing to 1 concurrent job and adding a 1 second sleep prior to making the call to create a PR.

FIX: Slow down rate even further

---

.github/workflows/update_ci.yml

Following up #17, the deploy rate is still too fast due to this being a content creation event (can generate notifications and be clamped down much faster). Going to make the job really really lazy (by computer standards anyway) and put a 10 second gap in between.

FIX: Make deploy workflow really lazy

---

.github/workflows/update_ci.yml

Renames the repository for Knowledge Explorer to `discourse-docs`

DEV: Rename Knowledge Explorer to Docs

---

.github/workflows/update_ci.yml
README.md

Triggering deploys manually isn't a big hassle, but allows us to commit/merge multiple things without automatically flooding all the repos. (and hitting API request limits 😉) 
The README assumes `main` branch so we need to rename after merging.

DEV: Move to a manual workflow trigger

---

workflow-templates/plugin-linting.yml

This means that if you have multiple failures, they can all be seen in a single run

FEATURE: Always run all linting tests in GitHub actions, even on failure

---

.github/workflows/update_ci.yml

It's a maintained official plugin so it should be tested, right?

Add discourse_bcc

---

workflow-templates/plugin-tests.yml

- Use discourse_test:slim images
- Use built-in postgres
- Cache migrated databases
- Remove postgres/ruby version from matrix - we use the ones in the docker image
(tested on a real plugin in https://github.com/discourse/discourse-solved/pull/178. In this case, test runtime improved from ~4mins to ~2mins)

DEV: Update plugin-tests workflow based on new core patterns

---

theme-workflow-templates/component-tests.yml
workflow-templates/plugin-tests.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

DEV: Update GitHub actions set-output uses

---

.github/workflows/discourse-plugin.yml

Previously we would initialize the job, install dependencies, and then skip tests if they were not present. This commit moves the check for existence into a separate super-fast job and then builds the test matrix dynamically based on the result.

discourse-plugin: Check for test types before initialising jobs

---

.github/workflows/discourse-plugin.yml
.github/workflows/discourse-theme.yml

The `git` version in our discourse_test docker image was recently updated to include a permissions check before running any git commands. For this to pass, the owner of the discourse directory needs to match the user running any git commands.
Under GitHub actions, by default the working directory is created with uid=1000 as the owner. We run all our tests as `root`, so this mismatch causes git to raise the permissions error. We can't switch to run the entire workflow as the `discourse (uid=1000)` user because our discourse_test image is not configured to allow `discourse` access to postgres/redis directories. For now, this commit updates the working directory's owner to match the user running the workflow.
See also https://github.com/discourse/discourse/pull/20069

DEV: Fix GitHub CI permissions issues

---

plugins.yml

discourse-newsletter-integration is an official plugin: https://github.com/discourse/discourse-newsletter-integration.

Add discourse-newsletter-integration plugin

---

.github/workflows/discourse-plugin.yml

The folder has moved as seen in https://github.com/discourse/discourse-post-voting/actions/runs/5953589402/job/16148190678?pr=159 and also in core https://github.com/discourse/discourse/blob/main/.github/workflows/tests.yml#L225-L227

DEV: Update system test screenshot path for test artifacts

---

.github/workflows/discourse-plugin.yml

In plugins that have no `scss,js,es6,hbs` files in `assets` folders, but have them `admin/assets`, the if-statement will still be true and runs only for `assets` folders.
This update makes sure we run both `assets` and `admin/assets` folders (and prevents this command from failing if there is only assets in `admin` but not `assets`).

DEV: Use correct folder when searching for assets to prettify

---

.github/workflows/discourse-theme.yml

Why this change?
Discourse core will soon support RSpec system tests for themes so we are
updating the workflow template here to support it as well.
I tested the new workflow on an existing theme with system tests which can be found [here](https://github.com/discourse/discourse-minimal-category-boxes/pull/26).

DEV: Support running system tests for themes

---

.github/workflows/discourse-theme.yml

Otherwise, we can end up restoring the development env database into the
test env database.

FIX: Include `RAILS_ENV` in theme test job cache key

---

.github/workflows/discourse-plugin.yml

Older versions of rubocop don't play well with 3.2. Wait with the upgrade until we update linting in all the repos.

FIX: Downgrade to ruby 3.1

---

.github/workflows/discourse-plugin.yml
.github/workflows/discourse-theme.yml

Since https://github.com/discourse/discourse/commit/7a8cbf8422c6eb4b4115f7e41ac9d6a9da688af2, Discourse core uses Ember 5 by default

Remove ember version matrix

---

.github/workflows/discourse-plugin.yml

Now that we updated rubocop in all plugin repos it should be good.

DEV: Update ruby to 3.2 again

---

.github/workflows/discourse-plugin.yml
.github/workflows/discourse-theme.yml

Updates the backend specs job run unconditionally, so that we run Zeitwerk and discourse-compatibility checks even if the plugin has no specs
Requires https://github.com/discourse/discourse/pull/26158

Add discourse-compatibility validation

---

.github/workflows/discourse-plugin.yml
.github/workflows/discourse-theme.yml

Why this change?
This is a follow-up to https://github.com/discourse/discourse/commit/99921120a1fe2d59e70036c85486c81325f36715
where both Chrome and Chromium are now installed in the test image as we
transition to using Chromium only in our test base image since supports both x86
and arm64 with binaries whereas Chrome still does not ship a binary for `linux/arm64`.

DEV: Remove Chrome before running tests

---

.github/workflows/discourse-plugin.yml
.github/workflows/discourse-theme.yml

Bundle cache should be keyed on ruby version as well as the debian release name. Changes to the debian release can affect the way gems are installed since gems may link to different versions of binaries.

DEV: Update actions cache keys for bundler

---

.github/workflows/discourse-theme.yml

As part of https://github.com/discourse/discourse/pull/26845, we are now
allowing theme developers to write end-to-end theme settings migration
tests. This means that we need to run all RSpec tests instead of just
system tests.

DEV: Update discourse-theme workflow to run all rspec tests

---

.github/workflows/discourse-plugin.yml
.github/workflows/discourse-theme.yml

In core's CI (which uses larger GitHub actions runners) this saved 7s. It should save even more time on theme/plugin CI, which tend to use the free runners with lower memory/cpu specs.

Enable cheap source maps for theme/plugin CI

---

.github/workflows/discourse-theme.yml

It would incorrectly try running specs when there were none (but there was a compat file)

FIX: Theme spec detection

---

.github/workflows/discourse-plugin.yml
.github/workflows/discourse-theme.yml

Allows running jobs with different `core_ref`s simultaneously

FIX: Add `core_ref` to the `group` key

---

.github/workflows/discourse-theme.yml

It was causing a borkout in db:create when a required plugin was trying to access the database in its initializer

FIX: Don't set `LOAD_PLUGINS` for all steps

---

.github/workflows/discourse-theme.yml

This adds steps to lint ruby files in the theme workflow. Dependent on https://github.com/discourse/DiscoTOC/pull/97.

DEV: add ruby linting steps to linting job in theme workflow

---

.github/workflows/discourse-plugin.yml

System specs that depend on S3 uploads are currently not supported on CI for plugins because MinIO, which is required for S3 system specs, isn't installed in the plugin tests workflow. This PR adds steps to install MinIO to support S3 system specs. See https://github.com/discourse-org/discourse-new-features-feeds/pull/47 for an example.

DEV: Add MinIO step for system specs

---

.github/workflows/discourse-theme.yml

We should be running `theme rspec` and `theme system` tests in parallel jobs and not within a single job.

Fix discourse-theme workflow not running system tests in another job

---

.github/workflows/discourse-plugin.yml
.github/workflows/discourse-theme.yml
.github/workflows/test-templates.yml

The following changes have also been made in this commit to support this change:
1. Introduce the `container` input so that the container used to run the various jobs can be configured.
2. Switch the `linting` job to either use the `container` input or `discourse/discourse_test:slim` so we don't have to require the runner VMs to have `ruby` or `npm` installed.

Use discourse self hosted runners for test-template workflow

---

.github/workflows/test-templates.yml

We have 8 and 16 cores runner now but 16 core runners are not quite
ready for prime time yet.

DEV: Update labels for our self hosted runners

---

.github/workflows/discourse-plugin.yml
.github/workflows/discourse-theme.yml

In the discourse_test container, the default shell is `dash`, which does not support some of the glob expansion we're doing here. In particular, that means that the eslint step has been broken. Making bash the default will fix that issue, and should reduce the chance of it happening again.

FIX: Set default shell to bash

---

.github/workflows/discourse-plugin.yml

This doesn't work because `tests/index.html` is not rebuilt with the correct plugins. Switching back to a full build for now.

FIX: Do not use pre-built assets for plugin qunit
